import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import * as XLSX from 'xlsx'
import { Download, FileSpreadsheet, Plus, RefreshCw, Trash2, Pencil } from 'lucide-react'
import { pkr, useSales } from '../context/SalesContext'

export default function SalesPipeline(){
  const {profile,records,users,loading,load,calc,deleteRecord}=useSales()
  const [search,setSearch]=useState(''),[person,setPerson]=useState(''),[status,setStatus]=useState(''),[prob,setProb]=useState('')
  const rows=useMemo(()=>records.filter(r=>{const p=Number(r.probability),txt=`${r.customer_name} ${r.item} ${r.vendor||''} ${r.profiles?.full_name||''}`.toLowerCase();return(!person||r.user_id===person)&&(!status||r.quotation_status===status)&&(!prob||(prob==='high'&&p>=67)||(prob==='medium'&&p>=34&&p<=66)||(prob==='low'&&p<=33))&&txt.includes(search.toLowerCase())}).map(r=>({...r,...calc(r)})),[records,search,person,status,prob,calc])
  async function remove(id){if(!confirm('Delete this opportunity?'))return;try{await deleteRecord(id)}catch(e){alert(e.message)}}
  function pdf(){if(!rows.length)return alert('No records available.');const doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'});doc.setFontSize(17);doc.text('TELEC GROUP - Sales Pipeline Report',14,14);doc.setFontSize(9);doc.text(`Generated: ${new Date().toLocaleString('en-GB')}`,14,21);autoTable(doc,{startY:27,head:[['#','Salesperson','Customer','Date','Item','Purchase','Sales','GST','Incl GST','WHT','Net','GP','Vendor','Terms','Prob','Status','Ageing']],body:rows.map((r,i)=>[i+1,r.profiles?.full_name,r.customer_name,r.quotation_date,r.item,r.purchase_value,r.sales_value_ex_gst,r.gst,r.incl,r.wht,r.net,r.gp,r.vendor,r.vendor_terms,`${r.probability}%`,r.quotation_status,`${r.age} days`]),styles:{fontSize:5.7,cellPadding:1.1}});doc.save('TELEC-Sales-Pipeline.pdf')}
  function excel(){const data=rows.map((r,i)=>({'S.No.':i+1,'Salesperson':r.profiles?.full_name,'Customer':r.customer_name,'Quotation Date':r.quotation_date,'Purchase Value':r.purchase_value,'Item':r.item,'Sales Value Excluding GST':r.sales_value_ex_gst,'GST':r.gst,'Sales Including GST':r.incl,'WHT':r.wht,'Net Total':r.net,'GP':r.gp,'Vendor':r.vendor,'Vendor Terms':r.vendor_terms,'Status':r.quotation_status,'Probability':r.probability,'Ageing':r.age,'Remarks':r.remarks}));const wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(data);XLSX.utils.book_append_sheet(wb,ws,'Sales Pipeline');XLSX.writeFile(wb,'TELEC-Sales-Pipeline.xlsx')}
  return <div><div className="topbar"><div><h1>Sales Pipeline</h1><p>Search, filter, edit and manage all opportunities</p></div><div className="actions"><button className="secondary" onClick={load}><RefreshCw size={16}/> Refresh</button><button className="secondary" onClick={pdf}><Download size={16}/> Export PDF</button>{profile.role==='admin'&&<button className="secondary" onClick={excel}><FileSpreadsheet size={16}/> Export Excel</button>}<Link className="primary button-link" to="/opportunity"><Plus size={16}/> Add Opportunity</Link></div></div>
  <section className="panel"><div className="filters four"><input placeholder="Search customer, item, vendor..." value={search} onChange={e=>setSearch(e.target.value)}/>{profile.role==='admin'&&<select value={person} onChange={e=>setPerson(e.target.value)}><option value="">All Salespersons</option>{users.filter(u=>u.role==='sales').map(u=><option key={u.id} value={u.id}>{u.full_name}</option>)}</select>}<select value={prob} onChange={e=>setProb(e.target.value)}><option value="">All probabilities</option><option value="high">High 67–100%</option><option value="medium">Medium 34–66%</option><option value="low">Low 0–33%</option></select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option>Pending</option><option>Submitted</option><option>Won</option><option>Lost</option><option>On Hold</option></select></div>
  <div className="table-wrap"><table className="wide-table"><thead><tr><th>#</th><th>Salesperson</th><th>Customer</th><th>Date</th><th>Item</th><th>Purchase</th><th>Sales Excl. GST</th><th>GST</th><th>Including GST</th><th>WHT</th><th>Net Total</th><th>GP</th><th>Vendor</th><th>Vendor Terms</th><th>Status</th><th>Probability</th><th>Ageing</th><th>Actions</th></tr></thead><tbody>{loading?<tr><td colSpan="18">Loading...</td></tr>:rows.map((r,i)=><tr key={r.id}><td>{i+1}</td><td>{r.profiles?.full_name}</td><td>{r.customer_name}</td><td>{r.quotation_date}</td><td>{r.item}</td><td>{pkr(r.purchase_value)}</td><td>{pkr(r.sales_value_ex_gst)}</td><td>{pkr(r.gst)}</td><td>{pkr(r.incl)}</td><td>{pkr(r.wht)}</td><td>{pkr(r.net)}</td><td>{pkr(r.gp)}</td><td>{r.vendor}</td><td>{r.vendor_terms}</td><td>{r.quotation_status}</td><td>{r.probability}%</td><td>{r.age} days</td><td><Link className="icon" to={`/opportunity/${r.id}`}><Pencil size={15}/></Link><button className="icon danger" onClick={()=>remove(r.id)}><Trash2 size={15}/></button></td></tr>)}</tbody></table></div></section></div>
}
